baseURL: 'https://sev3ryn.netlify.app'
languageCode: en
defaultContentLanguage: en

title: "Severyn Lisovskyi's Blog"
theme: LoveIt

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

author:
  name: "Severyn Lisovskyi"
  email: "sm.lisovsky@gmail.com"

menu:
  main:
  - name: "Blog"
    url: "/posts/"
    weight: 1
  - name: "About"
    url: "/about"
    weight: 2

markup:
  highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false

params:

  version: "0.2.X"
  description: "random thoughts"
  keywords: ["Blog"]
  images: ["/images/profile.png"]
  dateFormat: "02 Jan 2006"

  # search:
  #   enable: true
  list:
    dateFormat: "02 Jan 2006"
  section:
    dateFormat: "02 Jan 2006"

  header:
    title:
      name: "sev3ryn"
  footer:
    since: 2020
    hugo: true

  home:
    profile:
      avatarURL: "/images/profile.png"
      title: "Severyn Lisovskyi"
      subtitle: Sofware Engineer @ Opera Software
      social: true
      typeit: false

  social:
    GitHub: "sev3ryn"
    Linkedin: "slisovskyi"
    Twitter: "sev3ryn"
    Telegram: "sev3ryn"
    Email: "sm.lisovsky@gmail.com"
    RSS: true

  page:
    share:
      enable: true
      Twitter: true
      Reddit: true
    comment:
      enable: true
      # telegram:
      #   enable: true
      #   siteID: IU46e9Fy
      utterances:
        enable: true
        repo: "sev3ryn/myblog"
        label: "comment"

  analytics:
    enable: true
    google:
      id: UA-167432595-1
